// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Shared;

#nullable disable

namespace _Generate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("_Shared.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("date");

                    b.HasKey("PostId");

                    b.HasIndex("PublishedOn");

                    b.ToTable("posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Name = "Hello World",
                            PublishedOn = new DateTime(2022, 3, 20, 20, 42, 27, 94, DateTimeKind.Local).AddTicks(7744)
                        },
                        new
                        {
                            PostId = 2,
                            Name = "Hello World 2",
                            PublishedOn = new DateTime(2022, 3, 20, 20, 42, 27, 94, DateTimeKind.Local).AddTicks(7783)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
